language: android
dist: trusty
sudo: required
branches:
  only:
    - master
env:
  global:
    - >-
      otaLink=https://bigota.d.miui.com/8.4.28/miui_TISSOT_8.4.28_201ca5f229_8.1.zip
before_script:
  - 'echo | sudo add-apt-repository ppa:deadsnakes/ppa'
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get install -y python3.6
  - 'curl -O https://bootstrap.pypa.io/get-pip.py'
  - sudo python3.6 get-pip.py
  - python3.6 -m pip install --user google
  - python3.6 -m pip install --user protobuf
script:
  - export otaFileName="$(cut -d'/' -f5 <<<$otaLink)"
  - export releaseName="$(cut -d'/' -f4 <<<$otaLink)"
  - cd $TRAVIS_BUILD_DIR
  - time curl -O $otaLink
  - unzip $otaFileName -d extractedZip
  - mkdir -p 'otaExtractedFiles'
  - cd otaExtractedFiles
  - >-
    python3.6 $TRAVIS_BUILD_DIR/otaExtractScript/payload_dumper.py
    $TRAVIS_BUILD_DIR/extractedZip/payload.bin
  - zip fastboot-$releaseName.zip boot.img modem.img system.img
  - mv fastboot-$releaseName.zip $TRAVIS_BUILD_DIR/fastboot-$releaseName.zip
  - >-
    zip -ur "$TRAVIS_BUILD_DIR/TWRP Update Template v2.zip"
    $TRAVIS_BUILD_DIR/otaExtractedFiles/*
  - cd $TRAVIS_BUILD_DIR/otaExtractedFiles
  - ls -l
  - >-
    mv "$TRAVIS_BUILD_DIR/TWRP Update Template v2.zip"
    "$TRAVIS_BUILD_DIR/twrp-$releaseName.zip"
  - cd $TRAVIS_BUILD_DIR
  - ls -l
  - echo 'The files are $TRAVIS_BUILD_DIR/twrp-$releaseName.zip and $TRAVIS_BUILD_DIR/fastboot-$releaseName.zip'
deploy:
  provider: releases
  api_key:
    secure: >-
      u5ewz9jQArEs2Rpq7xOm9RzqWEMKE2asI4MPqT8vyOm+mcOp584QkDFkcOPSxl1YrYtLwPDfB3V+45VKJNruqJcHcWPoV15SSGQlawVnt+Gnl12S/g98wDmHBw+Wj1WTLtB1KJdM6nB9oQrfCOrG9UNcRbvPulKC0zIf5pifWYRIqKNxFk+txUygyIs8CszhvdiaPZNro1wsogxiazNvuJCjQ6cGZhADWXBIAMsZoDNmqxGBwypV+P/7yga0KX0mBsuxv2QTpmFKsmGyb3/1XB43SPhgrb6cBKMnn3ceWFOIxaiddeQ59pCkGzMg5lNNUqnXanIyzS/aVcZl2zsiyUsifTcnexxwFUHhdr31K1sNbJuPrKkBOS5VttVm6JWh+ubbnqnIrgwF6zKl8tnvwOq1SvML2xmwBAjVNGBXd251yjmtCy0x9in1dU0m4qbVfz2LWEhoGOkHVc8BsInicaXneFqlpREWxV4HbdsyF0cWJEPUNB+Ar6R84zvXZ/nlu8W1TneqaH9kcm5VYjwbLtlwtTOoMTmi3Gv52JIz1A0hWmoic96B4xewUgtDuGBJm2Lca1xpeZXwfXL0zMGYswExUAZfNePCyJiDI8ElvaFsOYQ9RP0gJhTMajN25BMDmd1P73h2IdcIk/54pE5Ol3bYJlTbykYlIEu+QZ24hZM=
  skip_cleanup: true
  file:
    - $TRAVIS_BUILD_DIR/twrp-$releaseName.zip
    - $TRAVIS_BUILD_DIR/fastboot-$releaseName.zip
  tag_name: $releaseName
  on:
    repo: 0reo27/Mi-A1-OTA-to-TWRP
notifications:
  email: false
